language: python

python:
  - "3.3"
  - "3.2"

install:
  - python setup.py install
  - pip install coveralls

script:
  - coverage run --source=wikibase setup.py test
  - coverage report -m

after_success:
  - coveralls